# Generated by Django 4.1.3 on 2022-11-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp',
            name='dept',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='department',
        ),
    ]
